const tracks=[
{title:"Pink Moon",artist:"KSTUDIO Selects",type:"Playlist",desc:"Soft pink pop for little happy moments.",img:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=85"},
{title:"Sugar Rush",artist:"Luna Vale",type:"Album",desc:"Sweet, sparkly pop with a little extra energy.",img:"https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=85"},
{title:"Cloudy Sunday",artist:"Mira Sol",type:"Album",desc:"Warm acoustic songs for a slow morning.",img:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=85"},
{title:"Bubblegum Nights",artist:"The Violets",type:"Album",desc:"Dreamy neon pop for late-night walks.",img:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=85"},
{title:"Little Things",artist:"Aria Bloom",type:"Single",desc:"A tiny song about noticing the good things.",img:"https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=85"}];
const artists=[["Luna Vale","https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80"],["Mira Sol","https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80"],["Aria Bloom","https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=400&q=80"],["The Violets","https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80"],["Nova Rey","https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=400&q=80"]];
const $=id=>document.getElementById(id);
$("albumsGrid").innerHTML=tracks.map(t=>`<article class="music" data-track="${t.title}"><div class="cover"><img src="${t.img}" alt="${t.title}" loading="lazy"></div><h3>${t.title}</h3><p>${t.artist} • ${t.type}</p></article>`).join("");
$("artistsGrid").innerHTML=artists.map(a=>`<article class="artist"><img src="${a[1]}" alt="${a[0]}" loading="lazy"><b>${a[0]}</b><small>Artist</small></article>`).join("");
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function play(name){let t=tracks.find(x=>x.title===name)||tracks[0];$("pimg").src=t.img;$("ptitle").textContent=t.title;$("partist").textContent=t.artist;$("player").style.display="flex";$("play").textContent="Ⅱ";toast("Playing ♡ "+t.title)}
function openModal(name){let t=tracks.find(x=>x.title===name)||tracks[0];$("mimg").src=t.img;$("mtype").textContent=t.type;$("mtitle").textContent=t.title;$("mdesc").textContent=t.desc;$("modal").classList.add("open");$("mplay").onclick=()=>{play(t.title);$("modal").classList.remove("open")}}
document.addEventListener("click",e=>{let p=e.target.closest("[data-play]");if(p)play(p.dataset.play);let o=e.target.closest("[data-open]");if(o)openModal(o.dataset.open);let m=e.target.closest("[data-track]");if(m)play(m.dataset.track)});
$("play").onclick=()=>{let b=$("play");b.textContent=b.textContent==="▶"?"Ⅱ":"▶";toast(b.textContent==="Ⅱ"?"Playing ♡":"Paused ♡")};$("close").onclick=()=>{$("player").style.display="none"};
$("searchBtn").onclick=()=>{$("search").classList.add("open");$("q").focus()};$("x").onclick=()=>$("search").classList.remove("open");
$("q").oninput=()=>{let q=$("q").value.toLowerCase();$("results").innerHTML=q?tracks.filter(t=>(t.title+" "+t.artist).toLowerCase().includes(q)).map(t=>`<div class="result" data-result="${t.title}"><b>${t.title}</b><br><small>${t.artist} • ${t.type}</small></div>`).join(""):"<p style='color:#b99faa'>Search a song or artist ♡</p>"};
$("results").onclick=e=>{let r=e.target.closest("[data-result]");if(r){$("search").classList.remove("open");openModal(r.dataset.result)}};
$("mx").onclick=()=>$("modal").classList.remove("open");document.addEventListener("keydown",e=>{if(e.key==="Escape"){$("search").classList.remove("open");$("modal").classList.remove("open")}});